### PR TITLE
slope_aes

### LINKED ISSUE #1200: diagonal line to work on log scale
I'm a huge fan of the diagonal line functionality.

For a scatter plot on a log scale, it doesn't seem to function. No diagonal line shows up with the following code.

```julia
using Gadfly, RDatasets, Compose
set_default_plot_size(14cm, 8cm)
plot(dataset("ggplot2", "mpg"),
     x="Cty", y="Hwy", label="Model", Geom.point, Geom.label,
     Scale.x_log10, Scale.y_log10,
     intercept=[0.0], slope=[1], Geom.abline(color="red", style=:dash),
     Guide.annotation(compose(context(), text(6,4, "y=x", hleft, vtop), fill("red"))))
```

### PR DESCRIPTION
**Pull request by Mattriks**
Fixes #1200.
This fix will work for transformations of the y-variable. As yet untested for transformations of both variables.

- [x] I've updated the documentation to reflect these changes
- [x] I've added an entry to `NEWS.md`
- [x] I've run the regression tests
- [ ] I've built the docs and confirmed these changes don't cause new errors

Here's my log-linear example from #1200.  In both plots, the `intercept=21` and `slope=-0.2`.
```
Random.seed!(123)
 x = 15*rand(20)
 D = DataFrame(x=x, y= exp.(-0.2*x.+3.03) .+ 0.2*randn(length(x)))

abline = Geom.abline(color="red", style=:dash)

pa = plot(D, x=:x, y=:y,  Geom.point, Scale.y_continuous,
      intercept=[21], slope=[-0.2],  abline )
pb = plot(D, x=:x, y=:y,  Geom.point, Scale.y_log,    
     intercept=[21], slope=[-0.2], abline )

draw(PNG(6inch,3inch), hstack(pa, pb))
```
iss1200b

### CODE REVIEW

**Comment by Mattriks** [comment]
I see the Travis build is failing: same error as johnmyleswhite/RDatasets.jl#61.

**Comment by tlnagy** [comment]
I think this is caused by recent changes in `CSV.jl`. Does it pass locally if you pin the version of CSV to v0.3.1?

**Comment by Mattriks** [comment]
Here are examples of transformations of both `y` and `x`:
```julia
Random.seed!(123)
 x = [20*rand(20); exp(-3)]
Da = DataFrame(x=x, y= (-0.5*sqrt.(x).+5).^2 .+ 0.1*randn(length(x)) )  
Db = DataFrame(x=x, y= exp.(-0.5*asinh.(x).+5) .+ 0.1*randn(length(x)) ) 
Dc = DataFrame(x=x, y= (-0.5*log.(x).+5).^2 .+ 0.1*randn(length(x)) ) 

abline = Geom.abline(color="red", style=:dash)

pa = plot(Da, x=:x, y=:y,  Geom.point,  Scale.x_sqrt, Scale.y_sqrt,
      intercept=[25], slope=[-0.5],  abline, Guide.title("T(x)=√x") )
pb = plot(Db, x=:x, y=:y,  Geom.point,  Scale.x_asinh, Scale.y_log,
     intercept=[148], slope=[-0.5], abline, Guide.title("T(x)=asinh(x)") )
pc = plot(Dc, x=:x, y=:y,  Geom.point,  Scale.x_log, Scale.y_sqrt,
    intercept=[25], slope=[-0.5], abline, Guide.title("T(x)=ln(x)") )
hstack(pa, pb, pc)
```
abline
It all works (e.g. plots a and b), with the caveat that plot c doesn't work in the sense that the `intercept=25` doesn't match the intercept at `x=0` (because `log_(x)` is asymptotic). This is a minor caveat: the slope in plot c is correct, and 25 is the intercept at `x=1` rather than `x=0`. I've updated the docs to tell users about the minor caveat.

**Comment by Mattriks** [comment]
Yes the tests pass locally with CSV 0.3.1.

**Comment by tlnagy** [comment]
> Yes the tests pass locally with CSV 0.3.1.

I think we should go ahead and merge because those changes aren't related to this PR

**Comment by Mattriks** [comment]
Ok!

**Pull request merged**
