### PR TITLE
Set Cairo compatibility

### LINKED ISSUE #1320: Cairo and Fontconfig incompatible with Gadfly
I need to use the Cairo and Fontconfig packages to export to png.
But they seem to be incompatible with Gadfly.

Running this code:
```
using Gadfly, Cairo, Fontconfig
plot(sin, 0, 6)
```
causes the error 
```
Error showing value of type Plot:
ERROR: TypeError: in typeassert, expected Compose.PangoLayout, got Nothing
```

I'm using Julia 1.1.1 with:
```
  "Fontconfig"       => v"0.2.0"
  "Gadfly"           => v"1.1.0"
  "Cairo"            => v"0.7.0"
```

### LINKED ISSUE #1324: ERROR: TypeError: in typeassert, expected Compose.PangoLayout, got Nothing
I have to pin cairo @ 0.6.0 to avoid this error.

### PR DESCRIPTION
**Pull request by CiaranOMara**
This PR resolves dependencies for #1339, closes #1320 and also closes #1324.

### CODE REVIEW

**Comment by bjarthur** [comment]
the docs have repeatedly failed to pass CI with his PR.  i've restarted multiple times and get the same "stalled build" error.  does this work for you locally?

worth noting that CategoricalArrays is now on v0.7, and Gadfly/Project.toml only lists 0.5.

**Comment by CiaranOMara** [comment]
My [Travis build](https://travis-ci.com/CiaranOMara/Gadfly.jl/builds/135788461) also stalled in the same spot.

However, the documentation did build locally.
image

Albeit, it took a while. I've prefixed the build with `travis_wait` (I may have put it in the wrong spot), which should let it keep running.

**Comment by Mattriks** [comment]
Does your local build of the docs use Compose master?

**Comment by CiaranOMara** [comment]
No it did not. It used the 7.4 release.
image

**Comment by CiaranOMara** [comment]
The difference that I'm aware of is that locally I used Julia v1.2 to build the doc instead of Julia v1.0. 

This Gadfly documentation build with Julia 1.2 got through in this [Travis job](https://travis-ci.com/CiaranOMara/Gadfly.jl/builds/135791275).

**Comment by CiaranOMara** [comment]
Commit https://github.com/GiovineItalia/Gadfly.jl/pull/1343/commits/a283bec77ef50ea924ea6276602041375dfb8603 got through in ~18min with `travis_wait`.

**Pull request merged**
