### PR TITLE
add a pull request template [ci skip]

### LINKED ISSUE #1117: NEWS.md is out of date
do we want to bring it up to date, or is it not that useful?

### PR DESCRIPTION
**Pull request by tlnagy**
This closes #1117

### CODE REVIEW

**Comment by tlnagy** [comment]
@bjarthur lmk if this works for you.

**Comment by bjarthur** [comment]
lgtm

**Comment by bjarthur** [comment]
[ ] I've run the regression tests
[ ] I've squash'ed or fixup'ed junk commits with git-rebase

**Comment by bjarthur** [comment]
[] I've built the docs and confirmed none of the examples throw any errors

**Pull request merged**
