### PR TITLE
DataFrames fixes

### LINKED ISSUE #1304: Tutorial not working (deprecation in dataframes.jl)
The tutorial page has this error, and I receive the same when attempting to follow it:

## Steps taken:
```
using Gadfly, RDatasets
iris = dataset("datasets", "iris")
p = plot(iris, x=:SepalLength, y=:SepalWidth, Geom.point);
```

## Result
```
┌ Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = evalmapping(::DataFrames.DataFrame, ::Symbol) at dataframes.jl:96
└ @ Gadfly ~/build/GiovineItalia/Gadfly.jl/src/dataframes.jl:96
```

### PR DESCRIPTION
**Pull request by Mattriks**
- [x] I've added an entry to `NEWS.md`
- [x] I've added and/or updated the unit tests
- [x] I've run the regression tests
- [x] I've built the docs and confirmed these changes don't cause new errors

### This PR:

- Fixes #1304 (`DataFrames` deprecated `df[:key]` syntax)
- Updates `dataframes.jl` file, testscripts, and docs
- This update might preserve Julia 0.7 compatability

### CODE REVIEW

**Comment by tlnagy** [comment]
This looks great! And thanks for taking the time to update the tests to the new API. I think this'll be an important stopgap change until we update everything to work with the new Tables API (https://github.com/GiovineItalia/Gadfly.jl/issues/1292). This is a more thorough update than either #1303 and #1313 so I'm going to merge this one in lieu of those.

**Comment by tlnagy** [comment]
> This update might preserve Julia 0.7 compatability

Did you try running the tests locally on Julia 0.7? I wasn't able to track down the `xparse` error (https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/585115113#L505) and master's tests pass for me locally on 0.7 (OpenSUSE Leap 15.1).

**Comment by Mattriks** [comment]
I need to update the docs too, so don't merge yet.

**Comment by tlnagy** [comment]
I wasn't going to merge until it passes on 0.7 locally, but yeah, I missed the lack of doc updates. That's needed to truly fix #1304

**Comment by Mattriks** [comment]
The `xparse` error is strange and appears to originate in Compose.jl [here](https://github.com/GiovineItalia/Compose.jl/blob/a081070de98b7c5d46bc4a0aaf19426a71489b8d/src/fontfallback.jl#L7).  There are also new deprecation warnings for Compose with Cairo 0.7, but that's a separate issue too.

**Comment by tlnagy** [comment]
Yeah, I tried tracking it down to this PR: https://github.com/JuliaIO/JSON.jl/pull/285#issuecomment-530144199 when the switch to the new API was made, but the tests pass so I'm sure why it's failing in Compose's tests.

**Comment by Mattriks** [comment]
I updated the docs, and they build locally, so this PR is ready to merge.

**Comment by Mattriks** [comment]
I also tracked down the `xparse` error. It happens when testing with Julia 0.7, because [Parsers.jl 0.2.22](https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/587972548#L481) gets installed. `xparse` is found in Parsers.jl 0.3 (not 0.2.22). So when testing on Julia 0.7, the incorrect version of Parsers.jl is getting installed. Note when testing Gadfly on Julia 1.x, Parsers.jl doesn't appear in the [Resolving package version...](https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/587972549#L476) listing.

**Comment by tlnagy** [comment]
> So when testing on Julia 0.7, the incorrect version of Parsers.jl is getting installed.

I installed Julia 0.7 locally and all the tests passed, it's only on Travis that I saw the `xparse` error...

> I updated the docs, and they build locally, so this PR is ready to merge.

awesome!

**Comment by Mattriks** [comment]
Parsers 0.2.22 doesn't have an `xparse` function, so does that mean the Gadfly tests will pass locally on Julia 0.7 if certain lines in Compose are not being evaluated (depending on things like system font setup?)

**Comment by tlnagy** [comment]
Ah, that makes sense.

> PR is ready to merge.

Lets do it.

**Comment by Mattriks** [comment]
@tlnagy The [dev docs](http://gadflyjl.org/dev/tutorial/#Arrays-1) haven't built.

**Comment by tlnagy** [comment]
That's due to the 0.7 builds failing (https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/589150627) and the doc build getting cancelled. I manually started the doc build, but that's not sustainable going forward.

**Comment by Mattriks** [comment]
Re the first option:  [Parsers.jl 0.3](https://github.com/JuliaData/Parsers.jl/blob/v0.3.0/Project.toml) (which has `xparse`) is compatible with Julia 0.7, so what's holding it back at Parsers 0.2.22?

**Comment by tlnagy** [comment]
Not sure, what's holding it back. Might be one of our dependencies

**Comment by Mattriks** [comment]
In the [`Resolving package versions...`](https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/589150627#L445) are there packages that are being added purely to setup the test?,  i.e. are some of the listed packages not in any way dependencies of Gadfly?

**Comment by tlnagy** [comment]
These are the only packages that are installed for tests in addition to the ones Gadfly directly depends on. 

https://github.com/GiovineItalia/Gadfly.jl/blob/aa4855ca7d113e31a51389edbfdd87cff15a60a2/Project.toml#L58-L68

**Comment by tlnagy** [comment]
It looks like maybe this is caused by https://github.com/JuliaStats/RDatasets.jl/pull/70 that dropped support for julia 0.7 and is maybe forcing the older version of `CSV` that requires the old `Parsers`?

I'm sure how to read the bounds exactly here: https://github.com/JuliaRegistries/General/blob/e69a570be9c66cbdd39c2d94e4e83e897f9000aa/R/RDatasets/Compat.toml#L52-L56

**Comment by Mattriks** [comment]
Compat.toml bounds: https://github.com/JuliaLang/Pkg.jl/issues/1190#issuecomment-526910989

**Pull request merged**
