### PR TITLE
fix render bug when aes.color_key_colors=nothing

### PR DESCRIPTION
**Pull request by dehann**
https://github.com/GiovineItalia/Gadfly.jl/blob/d507b208cab7da3dfd9104ada3a3d2281ef5646c/src/guide.jl#L399
check on `isempty(aes.color_key_colors==nothing)` produces a Julia base error:
```julia
julia> isempty(nothing)
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Base.RegexMatchIterator) at regex.jl:552
  iterate(::Base.RegexMatchIterator, ::Any) at regex.jl:552
  iterate(::LibGit2.GitBranchIter) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LibGit2/src/reference.jl:343
  ...
Stacktrace:
 [1] isempty(::Nothing) at ./essentials.jl:737
```
hence added a trivial test `aes.color_key_colors === nothing || isempty(aes.color_key_colors)`.

I had some trouble reproducing a MWE beyond the bigger block of working code I have, but either way there are several `=== nothing` checks in surrounding code already, and `isempty(nothing)` is a clear failure case.

# Contributor checklist:

- [ ] N/A I've updated the documentation to reflect these changes
- [x] I've added an entry to `NEWS.md`
- [ ] N/A I've added and/or updated the unit tests
- [x] I've run the regression tests
- [x] I've `squash`'ed or `fixup`'ed junk commits with git-rebase
- [x] I've built the docs and confirmed these changes don't cause new errors

-----

EDIT, 

#### Original error stack
```julia
ERROR: LoadError: LoadError: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::PyObject) at /home/dehann/.julia/packages/PyCall/zqDXB/src/pyiterator.jl:81
  iterate(::PyObject, ::Any) at /home/dehann/.julia/packages/PyCall/zqDXB/src/pyiterator.jl:81
  iterate(::Base.RegexMatchIterator) at regex.jl:552
  ...
Stacktrace:
 [1] isempty(::Nothing) at ./essentials.jl:737
 [2] render(::Gadfly.Guide.ColorKey, ::Theme, ::Gadfly.Aesthetics) at /home/dehann/.julia/dev/Gadfly/src/guide.jl:399
 [3] render(::Gadfly.Guide.ColorKey, ::Theme, ::Gadfly.Aesthetics, ::Bool) at /home/dehann/.julia/dev/Gadfly/src/guide.jl:143
 [4] render_prepared(::Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}; table_only::Bool, dynamic::Bool) at /home/dehann/.julia/dev/Gadfly/src/Gadfly.jl:817
 [5] render_prepared(::Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at /home/dehann/.julia/dev/Gadfly/src/Gadfly.jl:798
 [6] render(::Plot) at /home/dehann/.julia/dev/Gadfly/src/Gadfly.jl:744
 [7] #128 at ./none:0 [inlined]
 [8] iterate at ./generator.jl:47 [inlined]
 [9] collect at ./array.jl:686 [inlined]
 [10] hstack(::Plot, ::Plot) at /home/dehann/.julia/dev/Gadfly/src/Gadfly.jl:906
 [11] plotPose(::Pose2, ::Array{BallTreeDensity,1}, ::String; levels::Int64, c::Nothing, axis::Nothing, scale::Float64, overlay::Nothing, hdl::Array{Any,1}) at /home/dehann/.julia/dev/RoMEPlotting/src/RobotViz.jl:569
```

### CODE REVIEW

**Comment by Mattriks** [comment]
Does this error occur on Gadfly#master?  There's work currently being done on the discrete colorkey (#1385), which may solve the issue.  But it would be great if you could produce a basic example of the plot which produced the error, so we could better understand how the error originated.  We prefer fixing things by design, not by quick fixes.

**Comment by dehann** [comment]
After quite a bit of trying, i have not been able to simplify to a MWE yet -- takes my code a few hours to run and fail, and not worth deconstructing any further.  Although, it's pretty easy to see that calling `render` with `Gadfly.Aesthetics.color_key_colors=nothing` results in a `Base` error, because the function `isempty` is not being used correctly in this case.  But by simply adding an preceding additional logic test `=== nothing` to avoid the erroneous call `isempty(nothing)`, the plots render correctly as previous versions of the code have been doing for some time.

By the way, my use of Gadfly with has been working for years, so this error is new.  I think this issue is most likely something that was included in the last few months.

Are there any obvious circumstances in which `Gadfly.Aesthetics.color_key_colors=nothing` might occur, which could help find a MWE?  In my case it seems to originate from a fairly unsuspecting `hstack(pl1, pl2)`, however, I have not found yet what precisely about `pl1` and `pl2` causes `aes.color_key_colors` to  be `nothing`.

> We prefer fixing things by design, not by quick fixes.

I did not think this was just a quick fix:

https://github.com/GiovineItalia/Gadfly.jl/blob/d507b208cab7da3dfd9104ada3a3d2281ef5646c/src/aesthetics.jl#L61
and
https://github.com/GiovineItalia/Gadfly.jl/blob/d507b208cab7da3dfd9104ada3a3d2281ef5646c/src/misc.jl#L206

Seems to me `aes.color_key_colors` is allowed to be `nothing`.  So that is pretty clear that this can happen:
```julia
julia> isempty(nothing)
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Base.RegexMatchIterator) at regex.jl:552
  iterate(::Base.RegexMatchIterator, ::Any) at regex.jl:552
  iterate(::LibGit2.GitBranchIter) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LibGit2/src/reference.jl:343
  ...
Stacktrace:
 [1] isempty(::Nothing) at ./essentials.jl:737
```

If by design you mean that `aes.color_key_colors` can never be `nothing`, or the combination with other variables somehow sidesteps the problem, then there is likely a bigger issue with defining `color_key_colors::Union{Nothing, T}`.

**Comment by Mattriks** [comment]
By design, I mean as in #1469.  In fact the above issue might be fixed by the changes in #1469, which I'll merge this week.  Then you can retest to see if the issue still occurs.

**Comment by dehann** [comment]
Sure will do thanks, will try when that merges.  Must say, I don't immediately see how 1469 fixes the above issue, but happy to give it a try regardless.

**Comment by Mattriks** [comment]
I merged #1469, so if your plot contains a `Scale.color_none` you will get a deprecation warning.  If the above error still exists, I'd like to understand how it originates.

**Comment by dehann** [comment]
Hi @Mattriks, thanks.  I think #1469 does fix this problem I was having -- my older code now shows the deprecation warning which I can fix separately.  In addition though, I am still getting the problem from #1470 which I'm locally fixing with either the "smaller" fix in 1470, or defining a constructor as suggested here https://github.com/GiovineItalia/Gadfly.jl/pull/1470#issuecomment-671723558 .  Probably best to continue that discussion there in 1470.

**Pull request closed without merging**
