### PR TITLE
fix #1141

### LINKED ISSUE #1141: Bar placement with bar_spacing and orientation=:horizontal doesn't make sense
Bar placement relative to the grid seems to be completely off. Here is an example:

`a.csv`:

```
Name,X
Alice,15
Bob,11
```

`plot.jl`:

```julia
using Gadfly, DataFrames

df = readtable("a.csv")
df_tr = stack(df, [:X])

Gadfly.plot(df_tr, 
    x="value", y="Name", 
    Geom.bar(orientation= :horizontal), 
    Guide.xlabel(nothing),
    Guide.ylabel(nothing),
    Theme(
        bar_spacing=1cm, 
        key_position = :none))
```

Result:
hor

Vertical is perfectly fine, though: the bars are centered in the grid strips:
ver

### PR DESCRIPTION
**Pull request by ulysses4ever**
Fixes #1141

# Contributor checklist:

- [ ] I've updated the documentation to reflect these changes
- [ ] I've added an entry to `NEWS.md`
- [ ] I've added and/or updated the unit tests
- [x] I've run the regression tests
- [x] I've `squash`'ed or `fixup`'ed junk commits with git-rebase
- [ ] I've built the docs and confirmed these changes don't cause new errors

### CODE REVIEW

**Comment by bjarthur** [comment]
looks great.  i would suggest to include your broken example plot as a new unit test, or in your running of the regression tests did you find something equivalent?  if the latter, which one?  and thanks for taking the time to contribute!

**Comment by ulysses4ever** [comment]
I don't see any horizontal bar charts with spacing in the test suite. 

I'm I right that in order to add test case I should just add a script with `plot` inside in `test/testscripts`?

**Comment by bjarthur** [comment]
> I don't see any horizontal bar charts with spacing in the test suite.
>
>I'm I right that in order to add test case I should just add a script with `plot` inside in
`test/testscripts`?

correct!

**Comment by ulysses4ever** [comment]
Thanks! I've just found out that I ran test suite wrong (did `Pkg.test` once). So I'm going to rerun it properly and try to make sense from the `compare_examples.jl`'s output. Also I'm not sure if Julia indeed recompiles Gadfly when it switches between git-branches.

**Comment by tlnagy** [comment]
When you switch branches in the Gadfly folder (e.g. `~/.julia/v0.6/Gadfly/`), julia will automatically recompiling Gadfly when you do `Pkg.test("Gadfly")`. You check and make sure by running `using Gadfly` in the REPL right after switching the branch and you should see something like `INFO: Recompiling Gadfly`

**Comment by ulysses4ever** [comment]
Tests are failing with something strange
```
~/.julia/v0.6/Gadfly$ julia test/compare_examples.jl --bw .js.svg
...
Comparing density.js.svg ... same!
Comparing discrete_bar_horizontal.js.svg ... different :(
Couldn't get a file descriptor referring to the console
ERROR: LoadError: failed process: Process(`open /home/ulysses/.julia/v0.6/Gadfly/test/diffedoutput/discrete_bar_horizontal.js.svg.png`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] macro expansion at /home/ulysses/.julia/v0.6/Gadfly/test/compare_examples.jl:115 [inlined]
 [4] anonymous at ./<missing>:?
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /home/ulysses/.julia/v0.6/Gadfly/test/compare_examples.jl, in expression starting on line 69
```

**Comment by ulysses4ever** [comment]
Ubuntu Linux. I thought `open` is Mac-only thingy, isn't it?

**Comment by ulysses4ever** [comment]
It seems for Linux distros [you could try `xdg-open`](https://stackoverflow.com/a/264401/465100), and it seems, [Windows is out of luck](https://stackoverflow.com/q/501290/465100).

**Comment by ulysses4ever** [comment]
Here we are: only one chart has a diff after my fix, and this is, unsurprisingly, `discrete_bar_horizontal.jl`. Here is the image of the diff: on the right is “gennedoutput” (my fixed version), on the left is `master` (“cachedoutput”).

BTW: names `cached`/`genned` are hardly make much sense to me. I'd change for something like `master`/`devel`. But this is a matter for other issue, I guess…

**Comment by ulysses4ever** [comment]
(Sorry for the noise above) Added test case for horizontal bar chart with spacing.

**Comment by bjarthur** [comment]
looks great!  i will merge once the CI finishes.  for some reason it didn't run.

will also work on a PR for the two issues you mentioned above for `compare_examples`.  thanks for catching this.

**Comment by ulysses4ever** [comment]
I think CI was confused by my rebase and consequent push -f when adding test case. Good to know you actually ran it.

I was about to fix the issue with `open` actually. But if you already doing this, that's fine.

Thanks for the great library!

**Comment by bjarthur** [comment]
if you've already got a fix for `open` i'd say go ahead and submit a PR as i haven't started yet and am pretty busy with #1116.  i'd suggest using the already existing [`Gadfly.open_file`](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/Gadfly.jl#L1031).

i liked your suggestion to rename `cachedoutput` to `master-output` and `gennedoutput` to `devel-output`.  that could go in the same PR as a second commit.

**Comment by ulysses4ever** [comment]
Sure, give me a couple of days.

**Pull request merged**
