### PR TITLE
WIP:  unify size,shape,color aesthetics for Geom.point

### PR DESCRIPTION
**Pull request by bjarthur**
still to do

- [x] time the refactor of render(Geom.point).  could be a lot slower
- [x] figure out why Coord.cartesian is necessary when size aesthetic is specified
- [x] think about a better way to `classify_data` the size aesthetic other than Union'ing it with `:functional`
- [x] more tests

### CODE REVIEW

**Comment by Mattriks** [comment]
The size aesthetic currently works like so: `p = plot(x=1:5, y=randn(5), size=[x*mm for x in 1:5], Geom.point)
`. Are there new features anticipated here (apart from your 4 points above)?

**Comment by bjarthur** [comment]
better to describe this PR as unifying how Geom.point treats the size, shape, and color aesthetics.  so for example, this now works `plot(x=1:5, y=randn(5), size=[x*mm for x in 1:5], color=rand([colorant"red",colorant"blue"], 5), Geom.point)`.

**Comment by bjarthur** [comment]
can anyone explain why the Tick statistic takes into account the size aesthetic when setting axes limits?  i don't know of any geometry besides point which uses it.

**Comment by Mattriks** [comment]
The answer to your q might be because size is a property of points, and points are used frequently in plotting - they are the main geometry (and probably the first geometry that a developer would write). 

I have a new q: will this PR fix #918?

**Comment by tlnagy** [comment]
Oh yeah, #918 is nasty

**Comment by bjarthur** [comment]
think this is ready to merge.  please send comments.

one thing to note is that the compiling the docs is throwing a world age error on julia 0.6.  works fine on julia 0.5.  as Gadfly's tests pass, i presume this is a problem with Documenter.jl.

**Comment by tlnagy** [comment]
I'm going to try and give this a spin later today.


On Thu, Apr 27, 2017, at 11:11, Ben Arthur wrote:
> think this is ready to merge.  please send comments.
> 
> one thing to note is that the compiling the docs is throwing a world age
> error on julia 0.6.  works fine on julia 0.5.  as Gadfly's tests pass, i
> presume this is a problem with Documenter.jl.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/GiovineItalia/Gadfly.jl/pull/991#issuecomment-297795083
---
Tamas Nagy
Graduate Student, Bioinformatics
Weiner Lab
University of California, San Francisco 
http://tamasnagy.com

**Comment by tlnagy** [comment]
Ah shoot. I had totally forgotten about this. Everything looks good on my end.

**Comment by bjarthur** [comment]
i figured no news was good news ;)

**Pull request merged**
