### PR TITLE
Always set emit_on_finish to false in writemime

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by dcjones** [comment]
I'm not sure I understand why `emit_on_finish` should be set to false.

**Comment by shashi** [comment]
Is this related to https://github.com/dcjones/Compose.jl/pull/170 ?

**Comment by Keno** [comment]
Yes, I believe so.

**Comment by tlnagy** [comment]
I just confirmed that doesn't seem to fix https://github.com/GiovineItalia/Gadfly.jl/issues/747

**Pull request closed without merging**
