### PR TITLE
WIP:  update for julia 0.6

### PR DESCRIPTION
**Pull request by bjarthur**
tests are still failing to a macro call in Compose:

```
while loading /Users/arthurb/.julia/v0.6/Gadfly/test/runtests.jl, in expression starting on line 202
FAILED!
ERROR: LoadError: UndefVarError: codes not defined
Stacktrace:
 [1] macro expansion at /Users/arthurb/.julia/v0.6/Compose/src/misc.jl:125 [inlined]
 [2] jscall(::Array{String,1}, ::Array{Array{Measures.Measure,1},1}) at /Users/arthurb/.julia/v0.6/Compose/src/property.jl:587 (repeats 2 times)
 [3] (::Gadfly.Guide.##3#11{Array{Int64,1},Array{ColorTypes.Color,1},DataStructures.OrderedDict{ColorTypes.Color,AbstractString},Gadfly.Scale.#labeler#66,Compose.Context,Gadfly.Theme,Measures.Length{:mm,Float64},Measures.Length{:mm,Float64}})(::Compose.ParentDrawContext) at /Users/arthurb/.julia/v0.6/Gadfly/src/guide.jl:277
```

can anyone give me a hint here?

there is still also the `show` / `display` code to port.

### CODE REVIEW

**Comment by tlnagy** [comment]
That's not a very helpful error message...

**Comment by tlnagy** [comment]
Somehow I think that `codes` is not passing properly to this function and then the inner macro call. No idea why that is happening now. https://github.com/GiovineItalia/Compose.jl/blob/7ea1616cc084e6426bb5a6db422d564328cd6edd/src/property.jl#L585-L591

**Comment by bjarthur** [comment]
all tests pass now.

there are still some deprecation warnings though, mostly from FixedSizeArrays.jl, which Contour.jl uses.    we should consider switching to StaticArrays.jl at some point.  difficulty there is that it has dropped support for 0.5.

Media.jl also throws a couple warnings.

i would still suggest not merging this PR until folks have actually used it.  i have not actually visually checked the appearance of any plots yet to make sure they look okay.

**Comment by bjarthur** [comment]
wait, nevermind, the `codes not defined` error was reared it's head again...

**Comment by bjarthur** [comment]
the `codes not defined` error was a macro hygiene problem.  not sure how it ever worked on julia 0.5.  adding a few `esc()` got it working on 0.6.

now the tests are stuck on a world age problem...

**Comment by tlnagy** [comment]
Awesome! Thanks for finding that out. There seem to be a couple bugs in 0.5 that Gadfly/Compose relied on that were fixed in 0.6

**Comment by bjarthur** [comment]
the world age problem is now fixed, and all tests pass locally on julia 0.5 and 0.6!

would be great if someone could give it a try.  you'll need to checkout master on Loess, Hexagons, and Showoff, and checkout bja/julia06 on Compose and Gadfly.

there are still a couple depwarns from the Media.jl dependency, which is for Juno.

and a dozen or so depwarns remain from FixedSizeArrays.jl, which Contour.jl uses.  the plan is not to ever upgrade FixedSizeArrays.jl to julia 0.6, but rather to migrate everything that depends on it to StaticArrays.jl.

there are also quite a few `broadcast` depwarns, and a handful from `cycle`.  the file/line# info is not specific enough for me fix them.  i'm guessing they come from some dependency, perhaps FixedSizeArrays.

at any rate, as soon as my Compose PR is merged and tagged, the Gadfly tests should pass for this PR, and i think we can merge.

**Comment by tlnagy** [comment]
Is StaticArrays a drop in replacement for FixedSizeArrays? Because then we could move over to StaticArrays for both 0.5 and 0.6. Otherwise, we might have play around with conditional dependencies or something.

**Comment by bjarthur** [comment]
the names have changed, but otherwise it's drop-in.  whenever someone gets around to migrating Contour from FixedSizeArrays to StaticArrays, Gadfly will either have to drop support for julia 0.5 or add an upper bound on the Contour version.  until then, we just have to live with a few deprecation warnings.

**Comment by tlnagy** [comment]
StaticArrays appears to have 0.5 as the lower bound so we could probably migrate Contour right now.

**Comment by bjarthur** [comment]
[this](https://github.com/JuliaArrays/StaticArrays.jl/blob/master/REQUIRE) says 0.6-.  also, Contour.jl is in the [process](https://github.com/tlycken/Contour.jl/issues/37) of being moved to JuliaGeometry.

**Comment by tlnagy** [comment]
Ah, I missed that. I just read the README, but I guess that was out of date. I guess the moment that 0.6 drops we can make a final release for 0.5 and then move master solely to 0.6 and switch to staticarrays.

**Comment by ararslan** [comment]
Does anything else need to happen before you guys can make a 0.6-compatible tag of Gadfly?

**Comment by bjarthur** [comment]
someone should check that it works in the various IDEs... Juno, IJulia, JuliaBox.  i've only tested on the REPL.  specifically, Media.jl throws a few dep warns.

**Comment by ararslan** [comment]
IIRC the version of 0.6 on JuliaBox is pretty old so whether Gadfly works there is probably not entirely representative. If I may, I'd recommend that if it works in the REPL you'd might as well tag a version since mostly works is better than not working at all, and as Tony says, "tags are cheap."

**Comment by bjarthur** [comment]
@tlnagy @Mattriks either of you have any plans to submit PRs in the imminent future?  if not, we should tag a release.

**Comment by Mattriks** [comment]
Yes I hope to submit `Geom.vectorfield` (#608 & #791) say next week sometime.

**Comment by tlnagy** [comment]
As @tkelman says, tagging is cheap. Lets go ahead and go forward with tagging a release so we have 0.6 compat.

**Pull request merged**
