### PR TITLE
enhanced interactivity

### PR DESCRIPTION
**Pull request by bjarthur**
fixes https://github.com/GiovineItalia/Gadfly.jl/issues/816, https://github.com/GiovineItalia/Gadfly.jl/issues/731

1. enable rectangular (instead of just square) zoom boxes
2. enable panning with keyboard
3. add crosshair to display coordinates
4. keep marker size fixed whatever the zoom level is
5. keep labels in same relative position no matter the zoom level

~~~the last is in parens because i need some help.  specifically, how does one convert into Gadfly coordinates the x,y coords which SnapSVG provides?  and i have yet to figure out a way to display them in the plot window instead of the console.~~~  WIP.

~~~also,~~~ the zoom slider in the upper right with the plus/minus buttons has been removed, because the zoom scale is now a 2-tuple, for the x and y dimensions, so a single slider didn't make sense.  please let me know if you have a problem with this as it is a major change in the GUI.

### CODE REVIEW

**Comment by bjarthur** [comment]
@aviks @Mattriks @tlnagy @dcjones i think this is ready to merge.  as it's a big change to the pan/zoom API, could you please checkout this branch and give it a try?  you'll also need to checkout https://github.com/GiovineItalia/Compose.jl/pull/271.  thanks!

**Comment by tlnagy** [comment]
I finally got a chance to check this out. The good:

- Saner behavior with point sizes when zoomed in
- Weird scaling issues fixed 

The bad:

- I don't see any crosshair or coordinates?
- Zoom not very discoverable without the slider
- Disorienting a bit. I think something like ImageJ's minimap could help a bunch:

image

I made a quick movie showing my interaction with the plot: https://youtu.be/pIMe8djbhhA Does this look like it should? I checked out this branch and the Compose one and plotted from the REPL using `using Gadfly; plot(x=rand(100), y=rand(100), Geom.point, Geom.smooth)`

**Comment by bjarthur** [comment]
thanks for the comments.

the C key toggles on and off the display of the cursor coordinates in the upper right corner.

i agree it's not very discoverable, but it is clearly documented.

**Comment by bjarthur** [comment]
this is ready to merge i think.  @tlnagy i've made an attempt to make the features more discoverable.  could you please try it out again?  you'll need to checkout this PR plus Compose master.  thx.

**Comment by bjarthur** [comment]
the most recent commit in this PR makes the relative positions of labels invariant to zoom level.  give it a whirl!

also, re. adding an ImageJ-style minimap--  the ticks marks on the axes serve the same purpose, so i don't think that's needed here.  for an image, yes, but not for a plot.

**Comment by tlnagy** [comment]
I see a `?` in the upper right corner? It's present even when I toggle the coordinates off. I checked out the latest Compose master and this PR

image

**Comment by bjarthur** [comment]
the question mark is *not* present when the mouse is outside of the plot, correct?  and what happens when you press the question mark on the keyboard when the mouse is inside of the plot?

**Comment by tlnagy** [comment]
Ah.

image

I still think it's a little janky looking. Would it be possible to use something like `awesome-question-circle-o` from here: https://leungwensen.github.io/svg-icon/#awesome. It's SVG and looks like its MIT licensed too.

**Comment by tlnagy** [comment]
Great job btw, the interactivity is much improved.

Besides a couple aesthetic issues (the padding and color of the pop-up box) that we may disagree about, this PR is basically ready to merge.

**Comment by bjarthur** [comment]
thanks.  i used `distinguishable_colors` against the background color to make sure it was visible against a dark theme, no matter what they chose.

the padding is a pain.  i already hack it by adding `1px`.  not sure how to make that robust to scaling.

i could try the question mark SVG graphic.  at this point though, i'm kinda tired of working on this PR!  that plus there's so many other things to be done.

what are your thoughts on merging this before or after the DataFrames 11 PR?  there's very little overlap so i don't think the merge will be hard either way.  i'm inclined to do so before since support for julia 0.5 will be dropped.  i'd also like to tag a release right before DF11 is merged so that there's one final version before we drop support for 0.5

**Comment by tlnagy** [comment]
I'm okay with merging it as is. 

If I have some time, I'll see what I can do about the question mark. One PR doesn't have to do everything haha

**Comment by bjarthur** [comment]
i'll spend a little more time on the padding (both on the cursor coordinates and the help box) and the question mark before merging.

**Comment by tlnagy** [comment]
Okay. I've given a quick read-through and I'm okay with merging whenever you're satisfied with the tweaking. 👍

**Pull request merged**
