### PR TITLE
Fix Bug #822

### PR DESCRIPTION
**Pull request by trohwer**
I did not directly test on trunk, but made the same change on my local version, checking that it fixes the problem. Since it is a relative simple change without side effects, this is probably acceptable.

### CODE REVIEW

**Comment by tlnagy** [comment]
Thanks! We'll wait for the tests and then go ahead and merge.

**Comment by tlnagy** [comment]
Hey @bjarthur, any idea why the DateTime test is failing now? It's failing for me locally too, but it passed on master a week ago.

**Comment by tlnagy** [comment]
It might be due to some changes to Measures.jl

**Comment by bjarthur** [comment]
this is fixed in my 0.6 Gadfly PR.  just wait for it to merge.

**Comment by bjarthur** [comment]
re-doing travis

**Comment by bjarthur** [comment]
thanks for this @trohwer !

**Pull request merged**
