### PR TITLE
more Discrete Scale documentation

### PR DESCRIPTION
**Pull request by Mattriks**
- [x] I've updated the documentation
- [x] I've built the docs and confirmed these changes don't cause new errors

### This PR:
- adds documentation pertaining to #1366
- the main remaining point in #1366 is "issue 3" which I leave  to a future PR (size revamp).

### CODE REVIEW

**Comment by Mattriks** [comment]
Gadfly's Compose compat obviously needs to be bumped,. Would it also make things easier if common packages (e.g. Colors etc)  have the same compats?

**Comment by bjarthur** [comment]
herein lies the problem with the polling (instead of interrupt style) mechanism used by CompatHelper.  ideally the tagging of Compose should have triggered an immediate notification to Gadfly that it's compat section is out of date.  but Github permissions don't allow actions to post PRs to other repos.  so all CompatHelper do is poll periodically.  Gadfly and Compose are currently set to do so midnight on sunday, or whenever an issue is opened or re-opened.

**Comment by bjarthur** [comment]
just add another commit which updates Compose in compat.

**Comment by tlnagy** [comment]
> Gadfly and Compose are currently set to do so midnight on sunday, or whenever an issue is opened or re-opened.

Why can't we just poll daily? It would be nice to batch the updates more than that, but it's not really a hassle.

**Comment by bjarthur** [comment]
we could, i just figured it's a load on the servers that isn't warranted, despite being free.

**Comment by Mattriks** [comment]
Rebased and ready to merge.

**Pull request merged**
