### PR TITLE
Geom.violin with color

### PR DESCRIPTION
**Pull request by Mattriks**
Enables mapping violin color to a suitable variable (#1074).
An example:
```Julia
using DataFrames
group = ["S","A","T"]
D = vcat([DataFrame( y=(j-1)+randn(20), x=g*"$j", group=g)  for j in 1:2, g in group]...)
plot(D, x=:x, y=:y, Geom.violin, color=:group)
```
issue1074

### CODE REVIEW

**Comment by bjarthur** [comment]
looks great.  do you have time to update the documentation to mention that color is an aesthetic?

**Comment by Mattriks** [comment]
Ok, done.

**Comment by bjarthur** [comment]
thanks!

**Comment by Mattriks** [comment]
Great! Issues #1074 and #1018 can be closed

**Comment by bjarthur** [comment]
closed them.  next time, start your original post with "closes " and then the issue numbers and it will auto-close them when merged.  thanks again!

**Pull request merged**
