### PR TITLE
Switch from Iterators.jl to IterTools.jl

### PR DESCRIPTION
**Pull request by iamed2**
See ﻿https://github.com/JuliaCollections/Iterators.jl/issues/104

### CODE REVIEW

**Comment by tlnagy** [comment]
Thanks for submitting this PR!

**Comment by iamed2** [comment]
Thanks for merging! Check out https://github.com/GiovineItalia/Compose.jl/pull/259 if you have access there too.

**Comment by tlnagy** [comment]
Ah. I missed that one. It's merged too now

**Comment by iamed2** [comment]
Thanks!

**Comment by tkelman** [comment]
As with https://github.com/GiovineItalia/Compose.jl/pull/259, please tag this as soon as you can.

**Pull request merged**
