### PR TITLE
strip out old precompilation code

### PR DESCRIPTION
**Pull request by tlnagy**
AFAIK this isn't necessary anymore in recent versions of Julia. I can't detect any regressions and this dramatically increases precompilation speed:

Master:
```julia
julia> @time Base.compilecache("Gadfly")
INFO: Recompiling stale cache file /Users/tamasnagy/.julia/lib/v0.5/Gadfly.ji for module Gadfly.
 32.664419 seconds (310.71 k allocations: 12.912 MB)
"/Users/tamasnagy/.julia/lib/v0.5/Gadfly.ji"

julia> @time include("../test/points.jl")
  6.441102 seconds (8.14 M allocations: 338.343 MB, 5.44% gc time)

julia> @time include("../test/points.jl")
  0.005091 seconds (649 allocations: 56.553 KB)
```

This PR:
```julia
julia> @time Base.compilecache("Gadfly")
INFO: Recompiling stale cache file /Users/tamasnagy/.julia/lib/v0.5/Gadfly.ji for module Gadfly.
  7.503891 seconds (310.71 k allocations: 12.912 MB)
"/Users/tamasnagy/.julia/lib/v0.5/Gadfly.ji"

julia> @time include("../test/points.jl")
  6.620339 seconds (8.52 M allocations: 352.255 MB, 4.56% gc time)

julia> @time include("../test/points.jl")
  0.004820 seconds (649 allocations: 56.553 KB)
```

### CODE REVIEW

**Comment by tlnagy** [comment]
@bjarthur, @Mattriks, @shashi can you guys checkout this PR and give it a whirl? I wasn't able to get it to break on julia 0.5. (0.6 is broken regardless).

**Comment by bjarthur** [comment]
i notice a ~15% slow down the first time one draws to a file without `src/precompile`:

master:
```
jjulia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
 15.890677 seconds (14.52 M allocations: 614.291 MB, 1.47% gc time)

julia> using Gadfly

julia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
  0.029691 seconds (21.00 k allocations: 906.945 KB)

julia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
  0.028999 seconds (21.00 k allocations: 906.945 KB)
```

this PR:
```
julia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
 19.093611 seconds (20.67 M allocations: 859.435 MB, 2.48% gc time)

julia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
  0.025143 seconds (21.02 k allocations: 907.836 KB)

julia> @time draw(PDF("/tmp/foo.pdf",4inch,3inch), plot(y=[1,2,3],Geom.point))
  0.028570 seconds (21.02 k allocations: 907.836 KB)
```

as subsequent draws are comparable, i'd say merge it.

should probably reference https://github.com/GiovineItalia/Gadfly.jl/issues/921

**Comment by tlnagy** [comment]
Yeah, Gadfly still struggles with the first draw and we've had issues with that as long as I've worked on this project. @aviks' suggestion might be hitting on the problem in #921

**Comment by tlnagy** [comment]
Let's do this

**Comment by bjarthur** [comment]
should `src/precompile` be removed in `Compose` as well?

**Comment by tlnagy** [comment]
Good point, PR here: https://github.com/GiovineItalia/Compose.jl/pull/236. Increases initial precompilation speed by ~3x.

**Comment by timholy** [comment]
In the old days those files dropped the time-to-first-plot by a factor of 2, and so the time spent precompiling seemed well worth it. (You precompile "once," unless you're a developer, but you run many times.) Sounds like the advantage diminished with time?

**Comment by tlnagy** [comment]
Looks like it. Gadfly's time-to-first-plot is still embarrassingly slow (#921) and we still haven't been able to track down the problem. This PR only affects this first plot, the rest are basically instantaneous.

**Pull request merged**
