### PR TITLE
Update MIME type for show

### LINKED ISSUE #1316: MIME-type when plotting in Atom/Juno
The 1.0.1 version of Gadfly in the current version of Atom (1.40.1) produces the following warning:
  * Warning:   The "application/juno+plotpane" MIME type is deprecated. Please use "application/prs.juno.plotpane+html" instead.

# Atom Data

# Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.10.1
Config:
{
  "firstBoot": false,
  "juliaPath": "C:\\Users\\nritchie\\AppData\\Local\\Julia-1.2.0\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}

# ink:
Version: 0.11.0
Config:
undefined

# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.1
Config:
undefined

# language-weave:
Version: 0.6.4
Config:
undefined

# indent-detective:
Version: 0.4.0
Config:
undefined

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

    Status `C:\Users\nritchie\.julia\environments\v1.2\Project.toml`
  [1520ce14] AbstractTrees v0.2.1
  [c52e3926] Atom v0.9.1
  [6e4b80f9] BenchmarkTools v0.4.2
  [fe54227b] BoteSalvatICX v0.0.1 [`C:\Users\nritchie\.julia\dev\BoteSalvatICX`]
  [336ed68f] CSV v0.5.11
  [5ae59095] Colors v0.9.6
  [a93c6f00] DataFrames v0.19.3
  [1313f7d8] DataFramesMeta v0.5.0
  [31c24e10] Distributions v0.21.1
  [7876af07] Example v0.5.4 #master (https://github.com/JuliaLang/Example.jl.git)
  [10506e09] FFAST v0.0.1 [`C:\Users\nritchie\.julia\dev\FFAST`]
  [38e38edf] GLM v1.3.1
  [c91e804a] Gadfly v1.0.1
  [708ec375] Gumbo v0.5.1
  [cd3eb016] HTTP v0.8.5
  [7073ff75] IJulia v1.20.0
  [5903a43b] Infiltrator v0.1.0
  [43edad99] InstantiateFromURL v0.3.3
  [a98d9a8b] Interpolations v0.12.2
  [e5e0dc1b] Juno v0.7.2
  [e1d29d7a] Missings v0.4.1
  [5fb14364] OhMyREPL v0.5.2
  [7b2266bf] PeriodicTable v0.1.2
  [5ad8b20f] PhysicalConstants v0.2.0
  [f27b6e38] Polynomials v0.5.2
  [295af30f] Revise v2.1.9
  [028f657a] TotalLeastSquares v0.1.2
  [1986cc42] Unitful v0.16.0
  [37e2e46d] LinearAlgebra 
  [de0858da] Printf 
  [2f01184e] SparseArrays

### PR DESCRIPTION
**Pull request by jjerphan**
Fixes #1316

# Contributor checklist:
- [x] **I've updated the documentation to reflect these changes**: no change required
- [x] **I've added an entry to `NEWS.md`**
- [x] **I've added and/or updated the unit tests**: no need to.
- [x] **I've run the regression tests**: all the passing test on `master` pass on this branch
- [x] **I've `squash`'ed or `fixup`'ed junk commits with git-rebase**: one commit PR
- [x] **I've built the docs and confirmed these changes don't cause new errors**

# Proposed changes
- Resolves the deprecation

### CODE REVIEW

**Comment by tlnagy** [comment]
Thanks for the PR! Do you have a reference for when this change was made in Juno? It would be best to put a lower bound in the `[compat]` section of Project.toml for this change

**Comment by jjerphan** [comment]
@tlnagy: I don't know at all, I'll try to find it in Juno's history. :)

**Comment by jjerphan** [comment]
It comes from [this commit](https://github.com/JunoLab/Atom.jl/commit/9c4910b982d56b59857271bd350f4ce92de8b13e) in `Atom.jl`.

It seems that `v0.7.9` is the lower bound — I don't know whether I should add `Atom` in `Project.toml` or find the appropriate version of `Juno` that use this version of `Atom`.

**Comment by tlnagy** [comment]
Please don't add `Atom.jl` to `Project.toml`.

> find the appropriate version of `Juno` that uses this version of `Atom`.

This is the correct way. If compatible `Juno` versions don't have a hard lower bound against the `Atom`, I would file an issue with them since this would need to get fixed on their end.

**Comment by jjerphan** [comment]
It looks like it's `Atom.jl` that depends on `Juno.jl`:

https://github.com/JunoLab/Atom.jl/blob/f12e8765642ad6bbff7443a429a51bde3c1d2284/Project.toml#L44

**Comment by bjarthur** [comment]
@jjerphan thanks for taking the time to submit this PR!

i would suggest keeping both methods, so that Gadfly support both old and new versions of Atom.  so make a Union of those mime types:  `m::Union{MIME"application/juno+plotpane, MIME"application/prs.juno.plotpane+html"}"`

**Comment by jjerphan** [comment]
@bjarthur: I've performed this latter small change.

@tlnagy: just a little follow up on [my last comment](https://github.com/GiovineItalia/Gadfly.jl/pull/1322#issuecomment-535570059): what should be done regarding the compatibility with `Atom.jl`?

**Comment by bjarthur** [comment]
i don't think anything needs to be done with `[compat]`.  think this is fine as is and ready to go.

@tlnagy shall we merge?  just need to squash the two commits when we do.

**Comment by tlnagy** [comment]
Agreed.

**Pull request merged**
