### PR TITLE
bump to new minor version

### PR DESCRIPTION
**Pull request by bjarthur**

### CODE REVIEW

**Comment by matthieugomez** [comment]
Thanks! It's `@JuliaRegistrator` ;)

**Comment by Mattriks** [comment]
@bjarthur The v1.2 docs didn't appear at http://gadflyjl.org/stable/, and there's no v1.2 tag info (https://github.com/GiovineItalia/Gadfly.jl/tags). I know that v1.2 definitely exists.

 Is this [discourse post](https://discourse.julialang.org/t/travis-ci-configuration-breaking-changes/) related?

**Comment by bjarthur** [comment]
possibly.  there's also this [discourse post](https://discourse.julialang.org/t/ann-the-tagbot-github-app-is-deprecated-in-favour-of-the-tagbot-github-action/34344/6?u=bjarthur).

**Comment by bjarthur** [comment]
tagbot is also configured to only run [once per week](https://github.com/GiovineItalia/Gadfly.jl/blob/master/.github/workflows/TagBot.yml#L4).

**Comment by bjarthur** [comment]
the 1.2 docs seem to be there now.  not sure for how long...

**Pull request merged**
