### PR TITLE
Change to GitHub CI 

### LINKED ISSUE #1494: GitHub Actions CI
See:
https://discourse.julialang.org/t/easy-workflow-file-for-setting-up-github-actions-ci-for-your-julia-package/

### PR DESCRIPTION
**Pull request by rikhuijzer**
Fixes #1494

# Contributor checklist:

- [ ] I've updated the documentation to reflect these changes
- [ ] I've added an entry to `NEWS.md`
- [ ] I've added and/or updated the unit tests
- [ ] I've run the regression tests
- [ ] I've `squash`'ed or `fixup`'ed junk commits with git-rebase
- [x] I've built the docs and confirmed these changes don't cause new errors

# Proposed changes

- Switch from TravisCI to GitHub Actions.

### CODE REVIEW

**Comment by rikhuijzer** [comment]
Obviously, `GiovineItali/Gadfly.jl` has no runner setup and `rikhuijzer/Gadfly.jl` appears to also be missing a runner. Currently working on this at https://github.com/rikhuijzer/Gadfly2.jl.

**Comment by rikhuijzer** [comment]
Documentation works at https://rikhuijzer.github.io/Gadfly2.jl/dev/.

**Comment by rikhuijzer** [comment]
At this point, this branch seems to obtain the same CI outputs as the Travis configuration on `master`, so I'd say it's ready to merge.

**Comment by bjarthur** [comment]
LGTM.  @Mattriks ?

**Comment by bjarthur** [comment]
@rikhuijzer the docs built successfully after #1505 was merged, but they do not seem to have been deployed.  is that perhaps because [CI failed](https://urldefense.com/v3/__https://github.com/GiovineItalia/Gadfly.jl/actions/runs/434175021__;!!Eh6p8Q!WskeEkO6djG3Fvjg78zz5xCcWYKQLdLbNHvuFf9uxRxESpwYNkxubhoK7RWY$) for julia 1.0?  anyway to change github CI to fix it?  thanks.

**Comment by rikhuijzer** [comment]
@bjarthur Hmm, I should have checked the logs earlier. When looking at the GitHub Actions logs for the change to GitHub Workflow merge [1] and the most recent merged PR [2], I see
```
 ┌ Info: Deployment criteria:
 │ - ✔ ENV["TRAVIS_REPO_SLUG"]="" occurs in repo="github.com/GiovineItalia/Gadfly.jl.git"
 │ - ✘ ENV["TRAVIS_PULL_REQUEST"]="" is "false"
 │ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
 │ - ✘ ENV["TRAVIS_BRANCH"]="" matches devbranch="master" (if tag is empty)
 │ - ✘ ENV["DOCUMENTER_KEY"] exists
 │ - ✔ ENV["TRAVIS_EVENT_TYPE"]="" is not "cron"
 └ Deploying: ✘
```
So, it seems that `DOCUMETER_KEY` does not exist. Could you or someone else with the required permissions add this key? See the instructions in [3].

1: https://github.com/GiovineItalia/Gadfly.jl/runs/1397859352?check_suite_focus=true
2: https://github.com/GiovineItalia/Gadfly.jl/runs/1585199677?check_suite_focus=true
3: https://github.com/JuliaDocs/Documenter.jl/issues/1177#issuecomment-586662631

**Comment by bjarthur** [comment]
done.  but it still didn't deploy:

```
┌ Info: Deployment criteria:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="" occurs in repo="github.com/GiovineItalia/Gadfly.jl.git"
│ - ✘ ENV["TRAVIS_PULL_REQUEST"]="" is "false"
│ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
│ - ✘ ENV["TRAVIS_BRANCH"]="" matches devbranch="master" (if tag is empty)
│ - ✔ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="" is not "cron"
└ Deploying: ✘```

**Comment by rikhuijzer** [comment]
It seems that Documenter still looks for Travis, which isn't the case for the CI repository I made at https://github.com/rikhuijzer/Gadfly2.jl, there it says:
```
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="rikhuijzer/Gadfly2.jl" occurs in repo="github.com/rikhuijzer/Gadfly2.jl.git"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push"
│ - ✔ ENV["GITHUB_REF"] matches devbranch="master"
│ - ✔ ENV["GITHUB_ACTOR"] exists
│ - ✔ ENV["DOCUMENTER_KEY"] exists
└ Deploying: ✔
```
Lets hope that a newer Documenter version solves it, and if not, go from there.

**Pull request merged**
